version: "2"

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: billz
    volumes:
      - pgdata:/var/lib/postgresql/data

  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
  #   networks:
  #     - internal
  #   ports:
  #     - 6379:6379

  # localstack:
  #   image: localstack/localstack
  #   restart: unless-stopped
  #   ports:
  #     - "4566-4583:4566-4583"
  #   environment:
  #     SERVICES: s3
  #     DATA_DIR: /tmp/localstack/data
  #   volumes:
  #     - "./tmp:/tmp/localstack"

volumes:
  pgdata:

networks:
  internal:
    name: billz_network
    driver: bridge
